################################################################################
# Test file for HTTP routes of the API
# Needs REST Client VSCode addon
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################

### List opened events
GET http://localhost:3000/api/events

### Get one ticket infos by its name
GET http://localhost:3000/api/001/init

### Get all booked attractions to come for one visitor by ticket id
GET http://localhost:3000/api/3/bookings

### Insert new booking by ticket name
POST http://localhost:3000/api/001/book
content-type: application/json

{
    "number_places": 2,
    "attraction_id": 1,
    "visitor_id": 2
}
